#include "quantum_keycodes.h"
#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

#include "quantum.h"
#include "lib/oled.h"
#include "keymap_french_ergol.h"
#include "ergol_pics.h"

// Layer names for each layer
enum layers {
    _BASE,
    _ALTGR,
    _SYMB_NUM,
    _NAV_NUM,
    _MIR_FUNC,
    _MOUSE_NAV,
    _BOOT_RGB,
};

enum custom_keycodes {
    QMK_GO = SAFE_RANGE,
    QMK_GC,
};

// enum combos {CO_ESC, XMIN_ESC, GOGC_ESC, DDK_ENT, GCOM_ENT, ASSH_ENT};
enum combos {XMIN_ESC, DDK_ENT, GCOM_ENT, ASSH_ENT};

const uint16_t PROGMEM esc_combo2[] = {EL_X, EL_MINS, COMBO_END};
const uint16_t PROGMEM ent_combo1[] = {EL_D, EL_1DK , COMBO_END};
const uint16_t PROGMEM ent_combo2[] = {EL_G, EL_COMM, COMBO_END};
const uint16_t PROGMEM ent_combo3[] = {KC_PAST, KC_LPRN, COMBO_END};

combo_t key_combos[] = {
    [XMIN_ESC] = COMBO(esc_combo2, KC_ESC),
    [DDK_ENT]  = COMBO(ent_combo1, KC_ENT),
    [GCOM_ENT] = COMBO(ent_combo2, KC_ENT),
    [ASSH_ENT] = COMBO(ent_combo3, KC_ENT),
};

uint16_t last_key_press_time = 0;

// prevents combo activation if last key pressed within IDLE_BEFORE_COMBO
bool combo_should_trigger(uint16_t combo_index, combo_t *combo, uint16_t keycode, keyrecord_t *record) {
    if (timer_elapsed(last_key_press_time) < IDLE_BEFORE_COMBO) {
        return false;
    }
    return true;
}

bool is_flow_tap_key(uint16_t keycode) {
    if ((get_mods() & (MOD_MASK_CG | MOD_BIT_LALT)) != 0) {
        return false; // Disable Flow Tap on hotkeys.
    }
    switch (get_tap_keycode(keycode)) {
        // case KC_SPC:
        case KC_A ... KC_Z:
        case KC_DOT: // ,
        case KC_COMM: // G
        case KC_SCLN: // U
        case KC_SLSH: // K
            return true;
    }
    return false;
}

// french quotes with embedded non-breaking spaces
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case QMK_GO:
            if (record->event.pressed) {
                // when keycode QMK_GO is pressed
                SEND_STRING(SS_RSFT(SS_TAP(X_2) " "));
            } else {
                // when keycode QMK_GO is released
            }
            break;

        case QMK_GC:
            if (record->event.pressed) {
                // when keycode QMK_GC is pressed
                SEND_STRING(SS_RSFT(" " SS_TAP(X_3)));
            } else {
                // when keycode QMK_GC is released
            }
            break;
    }
    return true;
};

// CAPS_WORD
bool caps_word_press_user(uint16_t keycode) {
    switch (keycode) {
        // Keycodes that continue Caps Word, without shifting.
        case EL_1DK:
        case EL_1 ... EL_0:
        case KC_BSPC:
        case KC_DEL:
        case KC_RIGHT:
        case KC_LEFT:
        case EL_MINS:
            return true;

        // EL_V continues Caps Word, with shift applied.
        // ALTGR(EL_V) continues Caps Word, without shifting.
        case EL_V:
        case EL_A:
        case EL_E:
        case EL_S:
        case EL_N:
        case EL_P:
        case EL_W:
            // Apply shift if altgr is not activated.
            if (!(get_mods() & MOD_BIT(KC_RALT))) {
                add_weak_mods(MOD_BIT(KC_LSFT));
            }
            return true;

        // Keycodes that continue Caps Word, with shift applied.
        case EL_B:
        case EL_C:
        case EL_D:
        case EL_F:
        case EL_G:
        case EL_H:
        case EL_I:
        case EL_J:
        case EL_K:
        case EL_L:
        case EL_M:
        case EL_O:
        case EL_Q:
        case EL_R:
        case EL_T:
        case EL_U:
        case EL_X:
        case EL_Y:
        case EL_Z:
            if (get_mods() & MOD_BIT(KC_RALT)) { // Stop on altgr symbols
                return false;
            }
            add_weak_mods(MOD_BIT(KC_LSFT)); // Apply shift
            return true;

        // Stop on other keycodes
        default:
            return false;
    }
}

// following function not relevant with changed thumb keys (sticky ones)
// bool get_hold_on_other_key_press(uint16_t keycode, keyrecord_t *record) {
//     switch (keycode) {
//         case MT(MOD_RALT, KC_ENT):
//         case MT(MOD_LSFT, KC_BSPC):
//             // Immediately select the hold action when another key is pressed.
//             return true;
//         default:
//             // Do not select the hold action when another key is pressed.
//             return false;
//     }
// }

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_BASE] = LAYOUT_split_3x6_3( // 0
        //|--------+------+------------+------------+------------+--------------|                       |-------+------------+------------+------------+------------+--------------|
             KC_TAB,  EL_Q,        EL_C,        EL_O,        EL_P,          EL_W,                           EL_J,        EL_M,        EL_D,      EL_1DK,        EL_Y, RCTL(KC_BSPC),
        //|--------+------+------------+------------+------------+--------------|                       |-------+------------+------------+------------+------------+--------------|
              TO(2),  EL_A, GUI_T(EL_S), CTL_T(EL_E), ALT_T(EL_N),          EL_F,                           EL_L, ALT_T(EL_R), CTL_T(EL_T), GUI_T(EL_I), SFT_T(EL_U),        KC_END,
        //|--------+------+------------+------------+------------+--------------|                       |-------+------------+------------+------------+------------+--------------|
            KC_LGUI,  EL_Z,        EL_X,     EL_MINS,        EL_V,          EL_B,                         EL_DOT,        EL_H,        EL_G,     EL_COMM,        EL_K,        KC_DEL,
        //|--------+------+------------+------------+------------+--------------+--------------|  |-----+-------+------------+------------+------------+------------+--------------|
                                                           OSL(4), OSM(MOD_LSFT), LT(3,KC_BSPC),   LT(2,KC_SPC), OSL(1), LT(5,KC_ESC)
                                                         //`-----------------------------------'  `----------------------------------'
        ),

    [_ALTGR] = LAYOUT_split_3x6_3( // 1
        //|--------+-----------+-----------+-----------+-----------+-----------|                    |----------+-----------+-----------+--------------+-----------+--------------|
             KC_TAB, RALT(EL_Q), RALT(EL_C), RALT(EL_O), RALT(KC_R), RALT(KC_T),                     RALT(EL_J), RALT(EL_M), RALT(EL_D),    RALT(KC_O), RALT(EL_Y), RCTL(KC_BSPC),
        //|--------+-----------+-----------+-----------+-----------+-----------|                    |----------+-----------+-----------+--------------+-----------+--------------|
              TO(2), RALT(KC_A), RALT(EL_S), RALT(EL_E), RALT(EL_N), RALT(KC_G),                     RALT(EL_L), RALT(EL_R), RALT(EL_T),    RALT(EL_I), RALT(EL_U),        KC_END,
        //|--------+-----------+-----------+-----------+-----------+-----------|                    |----------+-----------+-----------+--------------+-----------+--------------|
            KC_LGUI, RALT(EL_Z), RALT(EL_X), RALT(KC_C), RALT(EL_V), RALT(EL_B),                     RALT(KC_N), RALT(EL_H), RALT(EL_G), RALT(EL_COMM), RALT(EL_K),        KC_DEL,
        //|--------+ ----------+-----------+-----------+-----------+-----------+--------|  ---------+----------+-----------+-----------+--------------+-----------+--------------|
                                                            KC_TRNS,    KC_TRNS,  KC_SPC,    KC_TRNS,    KC_ENT,    KC_TRNS
                                             //`----------------------------------------'  `-------------------------------'
        ),

    [_SYMB_NUM] = LAYOUT_split_3x6_3( // 2
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
            KC_TRNS, KC_EXLM,  QMK_GO,  QMK_GC,  KC_DLR, KC_PERC,                      KC_CIRC, KC_AMPR, KC_PAST, KC_LPRN, KC_RPRN, KC_TRNS,
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
              TO(0),    KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                         KC_6,    KC_7,    KC_8,    KC_9,    KC_0, KC_CALC,
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
            KC_TRNS, C(KC_Z),C(EL_X),C(KC_INS),S(KC_INS),   KC_M,                         KC_N, KC_PPLS, KC_PMNS,  KC_DOT, KC_PSLS,  KC_DEL,
        //|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
                                          KC_TRNS, KC_TRNS, LT(3,KC_BSPC),    KC_TRNS, KC_TRNS, KC_TRNS
                                        //`------------------------------'  `--------------------------'
        ),

    [_NAV_NUM] = LAYOUT_split_3x6_3( // 3
        //|--------+--------+--------+--------+--------+--------|                    |--------+------+------+------+--------+--------|
             KC_TAB, KC_CAPS, KC_HOME,   KC_UP,  KC_END, KC_PGUP,                      KC_PMNS,  KC_7,  KC_8,  KC_9, KC_PAST, KC_TRNS,
        //|--------+--------+--------+--------+--------+--------|                    |--------+------+------+------+--------+--------|
            KC_TRNS,  KC_TAB, KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN,                      KC_PPLS,  KC_4,  KC_5,  KC_6,    KC_0, KC_CALC,
        //|--------+--------+--------+--------+--------+--------|                    |--------+------+------+------+--------+--------|
            KC_TRNS, KC_WBAK, KC_PSCR,  KC_ESC,  KC_INS, KC_WFWD,                         KC_N,  KC_1,  KC_2,  KC_3,  KC_DOT,  KC_DEL,
        //|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+------+------+------+--------+--------|
                                                KC_TRNS, KC_TRNS, KC_TRNS,    KC_DEL , KC_PSLS, KC_TRNS
                                            //`--------------------------'  `--------------------------'
        ),

    [_MIR_FUNC] = LAYOUT_split_3x6_3( // 4
        //|--------+-----+------------+------------+------------+-------|                    |--------+--------+------+------+-------+--------|
            KC_WAKE, EL_Y,      EL_1DK,        EL_D,        EL_M,   EL_J,                      KC_VOLU,   KC_F7, KC_F8, KC_F9, KC_F10, KC_BRIU,
        //|--------+-----+------------+------------+------------+-------|                    |--------+--------+------+------+-------+--------|
            KC_SLEP, EL_U, GUI_T(EL_I), CTL_T(EL_T), ALT_T(EL_R),   EL_L,                      KC_VOLD,   KC_F4, KC_F5, KC_F6, KC_F11, KC_BRID,
        //|--------+-----+------------+------------+------------+-------|                    |--------+--------+------+------+-------+--------|
            KC_CNCL, EL_K,     EL_COMM,        EL_G,        EL_H, EL_DOT,                      KC_MUTE,   KC_F1, KC_F2, KC_F3, KC_F12,  KC_CLR,
        //|--------+-----+------------+------------+------------+-----------------|  |-------+--------+--------+------+------+-------+--------|
                                             KC_TRNS, OSM(MOD_LSFT), OSM(MOD_RALT),   KC_TRNS, KC_TRNS,   TG(6)
                                          //`-------------------------------------'  `-------------------------'
        ),

    [_MOUSE_NAV] = LAYOUT_split_3x6_3( // 5
        //|--------+--------+--------+--------+--------+--------|                  |--------+--------+--------+--------+--------+--------|
            KC_TRNS, KC_TRNS, KC_TRNS, MS_WHLU, KC_TRNS, KC_TRNS,                    KC_VOLU, MS_BTN1,   MS_UP, MS_BTN2, KC_TRNS, KC_TRNS,
        //|--------+--------+--------+--------+--------+--------|                  |--------+--------+--------+--------+--------+--------|
            KC_TRNS, KC_TRNS, MS_ACL0, MS_ACL1, MS_ACL2, KC_TRNS,                    KC_VOLD, MS_LEFT, MS_DOWN, MS_RGHT, MS_BTN1, KC_TRNS,
        //|--------+--------+--------+--------+--------+--------|                  |--------+--------+--------+--------+--------+--------|
            KC_TRNS, KC_TRNS, MS_WHLL, MS_WHLD, MS_WHLR, KC_TRNS,                    KC_MUTE, MS_BTN1, MS_BTN3, MS_BTN2, KC_TRNS, KC_TRNS,
        //|--------+--------+--------+--------+--------+--------+-------|  |-------+--------+--------+--------+--------+--------+--------|
                                                 TG(6), MS_BTN1, KC_BSPC,   KC_TRNS, KC_TRNS, KC_TRNS
                                            //`-------------------------'  `-------------------------'
        ),

    [_BOOT_RGB] = LAYOUT_split_3x6_3( // 6
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
            QK_BOOT, KC_TRNS, QK_MAKE, KC_TRNS, KC_TRNS,  EE_CLR,                      RM_VALU, RM_HUEU, RM_SATU, RM_NEXT, RM_TOGG,   TO(0),
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
              TO(0), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                      RM_VALD, RM_HUED, RM_SATD, RM_PREV, CK_TOGG,   TO(0),
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        //|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
                                                  TO(0),   TO(0),   TO(0),      TO(0),   TO(0),   TO(0)
                                            //`--------------------------'  `--------------------------'
        )
};


#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

#ifdef OLED_ENABLE

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    if (!is_keyboard_master()) {
        return OLED_ROTATION_270;
    }
    return rotation;
}

bool oled_task_user(void) {
    if (is_keyboard_master()) {
        if (get_highest_layer(layer_state) == _MIR_FUNC) {
            oled_write_raw_P(ergol_logo_base_img, sizeof(ergol_logo_base_img));
        } else {
            render_layer_state();
        }
    } else {
        switch (get_highest_layer(layer_state)) {
            case _BASE:
            case _ALTGR:
                oled_write_raw_P(ergol_logo_base_img, sizeof(ergol_logo_base_img));
                break;
            case _SYMB_NUM:
                oled_write_raw_P(ergol_logo_symbols_img, sizeof(ergol_logo_symbols_img));
                break;
            case _NAV_NUM:
                oled_write_raw_P(ergol_logo_navnum_img, sizeof(ergol_logo_navnum_img));
                break;
            case _MIR_FUNC:
                oled_write_raw_P(ergol_logo_symbols_img, sizeof(ergol_logo_symbols_img));
                break;
            case _MOUSE_NAV:
                oled_write_raw_P(ergol_logo_navnum_img, sizeof(ergol_logo_navnum_img));
                break;
            case _BOOT_RGB:
                oled_write_raw_P(ergol_logo_bootrgb_img, sizeof(ergol_logo_bootrgb_img));
                break;
        }
    }

    return false;
}

#endif // OLED_ENABLE
